### PR TITLE
File GET API, convenience methods and bug fixes

### PR DESCRIPTION
**Pull request by benwbrum**
These changes were created in order to import items from Omeka into FromThePage.

Features:
f2e23504053234ff4f8df09d9a4fbf8576970085 New File model
678fe8beeb734db4e3fd7ba84ae5cd51a9a813e7 ActiveRecord-style relationship methods
6979b70e3ea472d4327d5cbde60316aed0459228 ditto
3240df8fb4b8c17f709924072feb4a1df7337b06 Don't throw method_missing for attributes with no values.

Bug fixes:
5b205e5d301f424a216a64ebf29831559701880a Fixed a bug in which query parameters to GET calls were getting lost.
f7ef640875b9a56ff87b7bb1430e0c736ca89f50 Removed redundant code within method calls.

Refactoring:
898ba32eaf37f2a2846d66f1fe1b1c28cb7c9c02 Externalized the Omeka credentials used by the test code

### CODE REVIEW

**Comment by bibliotechy** [comment]
+1 on merging this PR and updating the gem. I've been using these additional features and would love to have them in the gem.

**Comment by lmullen** [comment]
@benwbrum I'm not actively working on this gem, and in fact have written a different client in R that I use more. Would you be interested in taking over maintenance responsibilities? You could at long last merge in your PR.

**Comment by bibliotechy** [comment]
@benwbrum I'd also be happy to help out with maintenance tasks if required.

**Comment by lmullen** [comment]
@bibliotechy I'd be glad for you to take over maintenance if you like. Let's give @benwbrum time to decide if he wants in. Next week I'll transfer admin rights to the repository to whomever wants it. Okay?

**Comment by benwbrum** [comment]
I vote for Chad. I don't run any Omeka installations, while Temple does.

**Comment by bibliotechy** [comment]
I'm fine with becoming maintainer for this gem.

**Comment by lmullen** [comment]
@bibliotechy It's settled, then. I'm glad to have you as the maintainer. I've given you push access to this repository. It's up to you whether you want to keep working here, fork the repo, or transfer it. I'll look into what needs to be done at Rubygems.

**Comment by lmullen** [comment]
@bibliotechy Looks like I just need your e-mail address to add you as an owner. Which e-mail address do you prefer?

**Comment by bibliotechy** [comment]
Great, thanks!

chad.nelson at temple.edu would work best.

**Comment by bibliotechy** [comment]
Actually...I think I'm registered on rubygems with my personal account. chadbnelson @ gmail.com, so you will probably need to use that one.

**Comment by lmullen** [comment]
@bibliotechy Looks like you've successfully been added as an owner on Rubygems, but feel free to let me know if there is any difficulty. Thanks very much for taking over the maintenance of the gem; I'm glad to see it is going to get continued use.

**Comment by benwbrum** [comment]
Hooray!

**Comment by lmullen** [comment]
:thumbsup:

**Pull request merged**
